eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
      
microservice:
  customer-service:
    endpoints:
      endpoint:
        uri: http://product-service/product/
